services:
  - type: web
    name: wealth-tracker
    env: docker
    plan: free
    envVars:
      - key: MONGODB_URL
        fromDatabase:
          name: wealth-tracker-db
          property: connectionString
databases:
  - name: wealth-tracker-db
    plan: free
